services:
  app:
    build:
      context: .
      args:
        DEV: "false"  # overridden in override file for dev
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: db
      DB_NAME: devdb
      DB_USER: devuser
      DB_PASS: changeme
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15.13-alpine3.20
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: devdb

volumes:
  dev-db-data: