name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for app (optional)
        run: sleep 5

      - name: Run Tests
        run: docker-compose exec -T app python manage.py test

      - name: Run Flake8 Lint
        run: docker-compose exec -T app flake8

      - name: Stop containers
        run: docker-compose down
